version: '3.9'

services:
##### Production #####
    # web:
    #     profiles: ["prod"]
    #     build: 
    #         context: web
    #         target: prod
    #     volumes:
    #         - demo:/web/dist
    #     depends_on:
    #         - nginx

    backend:
        profiles: ["prod"]
        build:
            context: backend
            target: prod

    web:
        profiles: ["prod"]
        build: 
            context: web
            target: prod
        volumes:
            - demo:/web/dist
        depends_on:
            - nginx

    nginx:
        profiles: ["prod"]
        image: nginx
        volumes:
            - demo:/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

##### Develop #####
    backend-dev:
        profiles: ["dev"]
        build:
            context: backend
            target: dev
        volumes:
            - ./backend:/backend
        ports:
            - 5000:5000

volumes:
    demo: